export enum TipoRotulo {
  APLICACAO = 'APLICACAO',
  PARECER_TUTORIA = 'PARECER_TUTORIA',
  PARECER_TUTORIA_PARTICIPANTE_CIENTE = 'PARECER_TUTORIA_PARTICIPANTE_CIENTE',
  PERSONALIZADO = 'PERSONALIZADO',
  STATUS_EVENTO = 'STATUS_EVENTO',
}
