export enum TipoAcao {
  ALTERA_LOCAL = 'ALTERA_LOCAL',
  ALTERA_TIPO = 'ALTERA_TIPO',
  ALTERA_TITULO = 'ALTERA_TITULO',
  ENCERRA_OCORRENCIA = 'FECHA_OCORRENCIA',
  REABRE_OCORRENCIA = 'REABRE_OCORRENCIA',
}
