export enum TipoAcao {
  ALTERA_LOCAL = 'ALTERA_LOCAL',
  ALTERA_ROTULO = 'ALTERA_ROTULO',
  ALTERA_TIPO = 'ALTERA_TIPO',
  ALTERA_TITULO = 'ALTERA_TITULO',
  ALTERA_UNIDADE = 'ALTERA_UNIDADE',
  ALTERA_VISIBILIDADE_EVENTO = 'ALTERA_VISIBILIDADE_EVENTO',
  ALTERA_VISIBILIDADE_INTERACAO = 'ALTERA_VISIBILIDADE_INTERACAO',
  ENCERRA_OCORRENCIA = 'FECHA_OCORRENCIA',
  REABRE_OCORRENCIA = 'REABRE_OCORRENCIA',
}
