export enum VisibilityType {
  CHOSEN_PARTICIPANTS = 'CHOSEN_PARTICIPANTS',
  AUTHOR_ONLY = 'AUTHOR_ONLY',
  MANAGERS_ONLY = 'MANAGERS_ONLY',
  PARTICIPANTS_ONLY = 'PARTICIPANTS_ONLY',
  ANYONE = 'ANYONE',
}
