export let CURSOS_FINANCEIRO: any = {};

CURSOS_FINANCEIRO['50923002'] = {
  COD_CURSO: 15,
  TURNO: 'MATUTINO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50923003'] = {
  COD_CURSO: 15,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50924002'] = {
  COD_CURSO: 16,
  TURNO: 'MATUTINO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50906003'] = {
  COD_CURSO: 15,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['60923002'] = {
  COD_CURSO: 15,
  TURNO: 'MATUTINO',
  UNIDADE: 'BUENO',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['401000000'] = {
  COD_CURSO: 15,
  TURNO: 'NOTURNO',
  UNIDADE: 'JOÃO MOURA',
  CIDADE: 'SÃO PAULO',
};
CURSOS_FINANCEIRO['60923003'] = {
  COD_CURSO: 15,
  TURNO: 'NOTURNO',
  UNIDADE: 'BUENO',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50931003'] = {
  COD_CURSO: 22,
  TURNO: 'MATUTINO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50931002'] = {
  COD_CURSO: 22,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50911002'] = {
  COD_CURSO: 6,
  TURNO: 'MATUTINO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50910002'] = {
  COD_CURSO: 5,
  TURNO: 'MATUTINO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['401000000'] = {
  COD_CURSO: 5,
  TURNO: 'NOTURNO',
  UNIDADE: 'JOÃO MOURA',
  CIDADE: 'SÃO PAULO',
};
CURSOS_FINANCEIRO['50910003'] = {
  COD_CURSO: 5,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50911003'] = {
  COD_CURSO: 6,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['60910002'] = {
  COD_CURSO: 5,
  TURNO: 'MATUTINO',
  UNIDADE: 'BUENO',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['60910003'] = {
  COD_CURSO: 5,
  TURNO: 'NOTURNO',
  UNIDADE: 'BUENO',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['60911003'] = {
  COD_CURSO: 6,
  TURNO: 'NOTURNO',
  UNIDADE: 'BUENO',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50930002'] = {
  COD_CURSO: 21,
  TURNO: 'MATUTINO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50930003'] = {
  COD_CURSO: 21,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50912004'] = {
  COD_CURSO: 7,
  TURNO: 'MATUTINO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['401000000'] = {
  COD_CURSO: 7,
  TURNO: 'MATUTINO',
  UNIDADE: 'JOÃO MOURA',
  CIDADE: 'SÃO PAULO',
};
CURSOS_FINANCEIRO['50912005'] = {
  COD_CURSO: 7,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['401000000'] = {
  COD_CURSO: 7,
  TURNO: 'NOTURNO',
  UNIDADE: 'JOÃO MOURA',
  CIDADE: 'SÃO PAULO',
};
CURSOS_FINANCEIRO['50917005'] = {
  COD_CURSO: 14,
  TURNO: 'MATUTINO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50917006'] = {
  COD_CURSO: 14,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50926002'] = {
  COD_CURSO: 17,
  TURNO: 'MATUTINO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50926003'] = {
  COD_CURSO: 17,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50925002'] = {
  COD_CURSO: 19,
  TURNO: 'MATUTINO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50925003'] = {
  COD_CURSO: 19,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50924003'] = {
  COD_CURSO: 16,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50928002'] = {
  COD_CURSO: 20,
  TURNO: 'MATUTINO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50928003'] = {
  COD_CURSO: 20,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50916008'] = {
  COD_CURSO: 23,
  TURNO: 'MATUTINO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50916009'] = {
  COD_CURSO: 23,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50908002'] = {
  COD_CURSO: 3,
  TURNO: 'MATUTINO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50908003'] = {
  COD_CURSO: 3,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50918005'] = {
  COD_CURSO: 13,
  TURNO: 'MATUTINO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['60918005'] = {
  COD_CURSO: 13,
  TURNO: 'MATUTINO',
  UNIDADE: 'BUENO',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50918006'] = {
  COD_CURSO: 13,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['60918006'] = {
  COD_CURSO: 13,
  TURNO: 'NOTURNO',
  UNIDADE: 'BUENO',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50922002'] = {
  COD_CURSO: 12,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50922003'] = {
  COD_CURSO: 12,
  TURNO: 'MATUTINO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50922004'] = {
  COD_CURSO: 12,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50909005'] = {
  COD_CURSO: 4,
  TURNO: 'MATUTINO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50909006'] = {
  COD_CURSO: 4,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['400923003'] = {
  COD_CURSO: 15,
  TURNO: 'NOTURNO',
  UNIDADE: 'JOÃO MOURA',
  CIDADE: 'SÃO PAULO',
};
CURSOS_FINANCEIRO['400910003'] = {
  COD_CURSO: 5,
  TURNO: 'NOTURNO',
  UNIDADE: 'JOÃO MOURA',
  CIDADE: 'SÃO PAULO',
};
CURSOS_FINANCEIRO['400905003'] = {
  COD_CURSO: 7,
  TURNO: 'MATUTINO',
  UNIDADE: 'JOÃO MOURA',
  CIDADE: 'SÃO PAULO',
};
CURSOS_FINANCEIRO['400905004'] = {
  COD_CURSO: 7,
  TURNO: 'NOTURNO',
  UNIDADE: 'JOÃO MOURA',
  CIDADE: 'SÃO PAULO',
};
CURSOS_FINANCEIRO['60911002'] = {
  COD_CURSO: 6,
  TURNO: 'MATUTINO',
  UNIDADE: 'BUENO',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['400905006'] = {
  COD_CURSO: 15,
  TURNO: 'NOTURNO',
  UNIDADE: 'JOÃO MOURA',
  CIDADE: 'SÃO PAULO',
};
CURSOS_FINANCEIRO['400905005'] = {
  COD_CURSO: 5,
  TURNO: 'NOTURNO',
  UNIDADE: 'JOÃO MOURA',
  CIDADE: 'SÃO PAULO',
};
CURSOS_FINANCEIRO['50916010'] = {
  COD_CURSO: 23,
  TURNO: 'MATUTINO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50916011'] = {
  COD_CURSO: 23,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['70910003'] = {
  COD_CURSO: 5,
  TURNO: 'NOTURNO',
  UNIDADE: 'CENTRO',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['70911003'] = {
  COD_CURSO: 6,
  TURNO: 'NOTURNO',
  UNIDADE: 'CENTRO',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['70923003'] = {
  COD_CURSO: 15,
  TURNO: 'NOTURNO',
  UNIDADE: 'CENTRO',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['50927003'] = {
  COD_CURSO: 18,
  TURNO: 'NOTURNO',
  UNIDADE: 'PERIMETRAL',
  CIDADE: 'GOIÂNIA',
};
CURSOS_FINANCEIRO['420909005'] = {
  COD_CURSO: 4,
  TURNO: 'MATUTINO',
  UNIDADE: 'JOÃO MOURA',
  CIDADE: 'SÃO PAULO',
};
